services:
  - type: web
    name: frontend
    env: node
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: serve -s build
    staticPublishPath: build
    rootDir: .
